
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team02-s26-05
owner: ucsb-cs156-s26
repo_name: team02-s26-05
pull_requests: [{"author":{"id":"U_kgDOCbzrWw","is_bot":false,"login":"katskt","name":"Katie"},"headRefName":"kp-recreq-edit-page","number":110,"title":"Kp recreq edit page","url":"https://github.com/ucsb-cs156-s26/team02-s26-05/pull/110"},{"author":{"id":"U_kgDOCbzrWw","is_bot":false,"login":"katskt","name":"Katie"},"headRefName":"kp-recreq-real-ages","number":109,"title":"Kp Recommendation Request Real Page Create","url":"https://github.com/ucsb-cs156-s26/team02-s26-05/pull/109"}]
