
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team02-s26-05
owner: ucsb-cs156-s26
repo_name: team02-s26-05
pull_requests: [{"author":{"id":"U_kgDOBZt3Dw","is_bot":false,"login":"ibrahimgok01","name":"Ibrahim Gok"},"headRefName":"ig-create-page-articles","number":83,"title":"IG - Create Page for Articles","url":"https://github.com/ucsb-cs156-s26/team02-s26-05/pull/83"},{"author":{"id":"U_kgDOCTjnkA","is_bot":false,"login":"JohnKim04","name":"John Kim"},"headRefName":"pc/helprequest-create","number":82,"title":"Create Page for HelpRequest plus tests and stories (#43)","url":"https://github.com/ucsb-cs156-s26/team02-s26-05/pull/82"},{"author":{"id":"U_kgDOCTjnkA","is_bot":false,"login":"JohnKim04","name":"John Kim"},"headRefName":"pc/helprequest-placeholders","number":81,"title":"Add HelpRequest placeholder pages, routes, and navbar (#42)","url":"https://github.com/ucsb-cs156-s26/team02-s26-05/pull/81"},{"author":{"id":"U_kgDOCTjnkA","is_bot":false,"login":"JohnKim04","name":"John Kim"},"headRefName":"pc/helprequest-table","number":80,"title":"Add HelpRequestTable component, tests, and stories (#41)","url":"https://github.com/ucsb-cs156-s26/team02-s26-05/pull/80"},{"author":{"id":"U_kgDOCTjnkA","is_bot":false,"login":"JohnKim04","name":"John Kim"},"headRefName":"pc/helprequest-form","number":79,"title":"Add HelpRequestForm component, tests, and stories (#40)","url":"https://github.com/ucsb-cs156-s26/team02-s26-05/pull/79"},{"author":{"id":"U_kgDOCTjnkA","is_bot":false,"login":"JohnKim04","name":"John Kim"},"headRefName":"pc/helprequest-fixtures","number":78,"title":"Add helpRequestFixtures.js (#39)","url":"https://github.com/ucsb-cs156-s26/team02-s26-05/pull/78"},{"author":{"id":"U_kgDOBZt3Dw","is_bot":false,"login":"ibrahimgok01","name":"Ibrahim Gok"},"headRefName":"ig-pages-articles","number":76,"title":"IG - Create, Edit, and Index Pages for Articles Table","url":"https://github.com/ucsb-cs156-s26/team02-s26-05/pull/76"}]
